import 'dart:async';

import 'package:floor/floor.dart';
import 'package:sqflite/sqflite.dart' as sqflite;

import 'converters/datetime_converter.dart';
import '../features/officers/data/dao/officer_dao.dart';
import '../features/officers/data/entities/officer_entity.dart';

// ⚡ Generated by floor_generator – run:
//    flutter pub run build_runner build --delete-conflicting-outputs
part 'app_database.g.dart';

@TypeConverters([DateTimeConverter, NullableDateTimeConverter])
@Database(version: 1, entities: [OfficerEntity])
abstract class AppDatabase extends FloorDatabase {
  // ── DAOs ──────────────────────────────────────────────────────────────────
  OfficerDao get officerDao;

  // ── Singleton builder ─────────────────────────────────────────────────────
  /// Call once in [main] via [ServiceLocator.init].
  static Future<AppDatabase> init() async {
    return $FloorAppDatabase
        .databaseBuilder('ncpd_database.db')
        .addMigrations([
          // Add future migrations here:
          // migration1to2,
        ])
        .build();
  }
}
