name: cyberpunk_ncpd
description: "A Flutter application that simulates a cyberpunk-themed police database, allowing users to search for and manage criminal records."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.11.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0
  floor: ^1.5.0
  sqflite: ^2.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.5.0
  build_runner: ^2.4.6
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true